//
//  words.c
//  Test strings for testing font rendering
//
//  Created by Matt Hartley on 18/06/2024.
//  Copyright 2024 GiantJelly. All rights reserved.
//

#define WORDS "aaron abduct accidental adjacent afghan after aint anaheim and anybody although allotted ambidextrous amend announced aqua arrangement ask aspin ate attitude authorised avery award axolotl baby baghdad banana batty beeped bent billow bizarre blood bottle bowwow boxed boyfriend bubbly buzzing byproduct bystander byzantine cappuccino cattle cent cicero coccyx cooked copyright coyote croquet cumbersome cycle cylinder czech dabble daddy day divide don't dr during dyke each ebb eek elephant emblem ensnare epiphany esquire etching equine farming feared filler fizzy fabric farming feared filler finger fjord fluid foggy foxxy frontal fungal gaggle geared gnome grubby happened happiness hazy hellish high hope hungry hyphen icy i'm impossible intolerant it's i've jazzy jagged jenga jill joint just kangaroo kettle kitchen knack koala kooky laboratory landing left letter likely lilac little loco lolly lover's luna luxurious lying master matter metres miss moonlight morph mr mrs ms mummy muster nasal neanderthal necessarily nine nonsense noon numb oar obfuscate occult oddly often ogre okay omission ozone parallel pear picnic pneumonic poppy porous pygmy quantum queen quince quota radii rafferty rattle reassure resist retiree rice roommate running sassafras savvy scent scuttle seismic shining shook sieve sister skink slump snide soup spire stay subject sultana svelte swiftly tallied tattooed taxed tension the theatre title totally trekked tsunami tutor tying udder ugly ulcer umbrella under usurp utterly vacuum variable vent vivid void vulnerable vying waffle wally warranted water weather whale wince withheld worry wurst wysiwyg wyvern xenon xmas yak yeah yip you're yuck zac zeal zigzag zing zodiac zoo \n"
#define WORDS_CAP "Aaron Abduct Accidental Adjacent Afghan After Aint Anaheim And Anybody Although Allotted Ambidextrous Amend Announced Aqua Arrangement Ask Aspin Ate Attitude Authorised Avery Award Axolotl Baby Baghdad Banana Batty Beeped Bent Billow Bizarre Blood Bottle Bowwow Boxed Boyfriend Bubbly Buzzing Byproduct Bystander Byzantine Cappuccino Cattle Cent Cicero Coccyx Cooked Copyright Coyote Croquet Cumbersome Cycle Cylinder Czech Dabble Daddy Day Divide Don't Dr During Dyke Each Ebb Eek Elephant Emblem Ensnare Epiphany Esquire Etching Equine Farming Feared Filler Fizzy Fabric Farming Feared Filler Finger Fjord Fluid Foggy Foxxy Frontal Fungal Gaggle Geared Gnome Grubby Happened Happiness Hazy Hellish High Hope Hungry Hyphen Icy I'm Impossible Intolerant It's I've Jazzy Jagged Jenga Jill Joint Just Kangaroo Kettle Kitchen Knack Koala Kooky Laboratory Landing Left Letter Likely Lilac Little Loco Lolly Lover's Luna Luxurious Lying Master Matter Metres Miss Moonlight Morph Mr Mrs Ms Mummy Muster Nasal Neanderthal Necessarily Nine Nonsense Noon Numb Oar Obfuscate Occult Oddly Often Ogre Okay Omission Ozone Parallel Pear Picnic Pneumonic Poppy Porous Pygmy Quantum Queen Quince Quota Radii Rafferty Rattle Reassure Resist Retiree Rice Roommate Running Sassafras Savvy Scent Scuttle Seismic Shining Shook Sieve Sister Skink Slump Snide Soup Spire Stay Subject Sultana Svelte Swiftly Tallied Tattooed Taxed Tension The Theatre Title Totally Trekked Tsunami Tutor Tying Udder Ugly Ulcer Umbrella Under Usurp Utterly Vacuum Variable Vent Vivid Void Vulnerable Vying Waffle Wally Warranted Water Weather Whale Wince Withheld Worry Wurst Wysiwyg Wyvern Xenon Xmas Yak Yeah Yip You're Yuck Zac Zeal Zigzag Zing Zodiac Zoo \n"
#define WORDS_UPPER "AARON ABDUCT ACCIDENTAL ADJACENT AFGHAN AFTER AINT ANAHEIM AND ANYBODY ALTHOUGH ALLOTTED AMBIDEXTROUS AMEND ANNOUNCED AQUA ARRANGEMENT ASK ASPIN ATE ATTITUDE AUTHORISED AVERY AWARD AXOLOTL BABY BAGHDAD BANANA BATTY BEEPED BENT BILLOW BIZARRE BLOOD BOTTLE BOWWOW BOXED BOYFRIEND BUBBLY BUZZING BYPRODUCT BYSTANDER BYZANTINE CAPPUCCINO CATTLE CENT CICERO COCCYX COOKED COPYRIGHT COYOTE CROQUET CUMBERSOME CYCLE CYLINDER CZECH DABBLE DADDY DAY DIVIDE DON'T DR DURING DYKE EACH EBB EEK ELEPHANT EMBLEM ENSNARE EPIPHANY ESQUIRE ETCHING EQUINE FARMING FEARED FILLER FIZZY FABRIC FARMING FEARED FILLER FINGER FJORD FLUID FOGGY FOXXY FRONTAL FUNGAL GAGGLE GEARED GNOME GRUBBY HAPPENED HAPPINESS HAZY HELLISH HIGH HOPE HUNGRY HYPHEN ICY I'M IMPOSSIBLE INTOLERANT IT'S I'VE JAZZY JAGGED JENGA JILL JOINT JUST KANGAROO KETTLE KITCHEN KNACK KOALA KOOKY LABORATORY LANDING LEFT LETTER LIKELY LILAC LITTLE LOCO LOLLY LOVER'S LUNA LUXURIOUS LYING MASTER MATTER METRES MISS MOONLIGHT MORPH MR MRS MS MUMMY MUSTER NASAL NEANDERTHAL NECESSARILY NINE NONSENSE NOON NUMB OAR OBFUSCATE OCCULT ODDLY OFTEN OGRE OKAY OMISSION OZONE PARALLEL PEAR PICNIC PNEUMONIC POPPY POROUS PYGMY QUANTUM QUEEN QUINCE QUOTA RADII RAFFERTY RATTLE REASSURE RESIST RETIREE RICE ROOMMATE RUNNING SASSAFRAS SAVVY SCENT SCUTTLE SEISMIC SHINING SHOOK SIEVE SISTER SKINK SLUMP SNIDE SOUP SPIRE STAY SUBJECT SULTANA SVELTE SWIFTLY TALLIED TATTOOED TAXED TENSION THE THEATRE TITLE TOTALLY TREKKED TSUNAMI TUTOR TYING UDDER UGLY ULCER UMBRELLA UNDER USURP UTTERLY VACUUM VARIABLE VENT VIVID VOID VULNERABLE VYING WAFFLE WALLY WARRANTED WATER WEATHER WHALE WINCE WITHHELD WORRY WURST WYSIWYG WYVERN XENON XMAS YAK YEAH YIP YOU'RE YUCK ZAC ZEAL ZIGZAG ZING ZODIAC ZOO \n"
char* ALL_THE_WORDS =
// "aaron abduct accidental adjacent afghan after aint anaheim and anybody although allotted ambidextrous amend announced aqua arrangement ask aspin ate attitude authorised avery award axolotl baby baghdad banana batty beeped bent billow bizarre blood bottle bowwow boxed boyfriend bubbly buzzing byproduct bystander byzantine cappuccino cattle cent cicero coccyx cooked copyright coyote croquet cumbersome cycle cylinder czech dabble daddy day divide don't dr during dyke each ebb eek elephant emblem ensnare epiphany esquire etching equine farming feared filler fizzy fabric farming feared filler finger fjord fluid foggy foxxy frontal fungal gaggle geared gnome grubby happened happiness hazy hellish high hope hungry hyphen icy i'm impossible intolerant it's i've jazzy jagged jenga jill joint just kangaroo kettle kitchen knack koala kooky laboratory landing left letter likely lilac little loco lolly lover's luna luxurious lying master matter metres miss moonlight morph mr mrs ms mummy muster nasal neanderthal necessarily nine nonsense noon numb oar obfuscate occult oddly often ogre okay omission ozone parallel pear picnic pneumonic poppy porous pygmy quantum queen quince quota radii rafferty rattle reassure resist retiree rice roommate running sassafras savvy scent scuttle seismic shining shook sieve sister skink slump snide soup spire stay subject sultana svelte swiftly tallied tattooed taxed tension the theatre title totally trekked tsunami tutor tying udder ugly ulcer umbrella under usurp utterly vacuum variable vent vivid void vulnerable vying waffle wally warranted water weather whale wince withheld worry wurst wysiwyg wyvern xenon xmas yak yeah yip you're yuck zac zeal zigzag zing zodiac zoo \n"
"Aaron Abduct Accidental Adjacent Afghan After Aint Anaheim And Anybody Although Allotted Ambidextrous Amend Announced Aqua Arrangement Ask Aspin Ate Attitude Authorised Avery Award Axolotl Baby Baghdad Banana Batty Beeped Bent Billow Bizarre Blood Bottle Bowwow Boxed Boyfriend Bubbly Buzzing Byproduct Bystander Byzantine Cappuccino Cattle Cent Cicero Coccyx Cooked Copyright Coyote Croquet Cumbersome Cycle Cylinder Czech Dabble Daddy Day Divide Don't Dr During Dyke Each Ebb Eek Elephant Emblem Ensnare Epiphany Esquire Etching Equine Farming Feared Filler Fizzy Fabric Farming Feared Filler Finger Fjord Fluid Foggy Foxxy Frontal Fungal Gaggle Geared Gnome Grubby Happened Happiness Hazy Hellish High Hope Hungry Hyphen Icy I'm Impossible Intolerant It's I've Jazzy Jagged Jenga Jill Joint Just Kangaroo Kettle Kitchen Knack Koala Kooky Laboratory Landing Left Letter Likely Lilac Little Loco Lolly Lover's Luna Luxurious Lying Master Matter Metres Miss Moonlight Morph Mr Mrs Ms Mummy Muster Nasal Neanderthal Necessarily Nine Nonsense Noon Numb Oar Obfuscate Occult Oddly Often Ogre Okay Omission Ozone Parallel Pear Picnic Pneumonic Poppy Porous Pygmy Quantum Queen Quince Quota Radii Rafferty Rattle Reassure Resist Retiree Rice Roommate Running Sassafras Savvy Scent Scuttle Seismic Shining Shook Sieve Sister Skink Slump Snide Soup Spire Stay Subject Sultana Svelte Swiftly Tallied Tattooed Taxed Tension The Theatre Title Totally Trekked Tsunami Tutor Tying Udder Ugly Ulcer Umbrella Under Usurp Utterly Vacuum Variable Vent Vivid Void Vulnerable Vying Waffle Wally Warranted Water Weather Whale Wince Withheld Worry Wurst Wysiwyg Wyvern Xenon Xmas Yak Yeah Yip You're Yuck Zac Zeal Zigzag Zing Zodiac Zoo \n"
// "AARON ABDUCT ACCIDENTAL ADJACENT AFGHAN AFTER AINT ANAHEIM AND ANYBODY ALTHOUGH ALLOTTED AMBIDEXTROUS AMEND ANNOUNCED AQUA ARRANGEMENT ASK ASPIN ATE ATTITUDE AUTHORISED AVERY AWARD AXOLOTL BABY BAGHDAD BANANA BATTY BEEPED BENT BILLOW BIZARRE BLOOD BOTTLE BOWWOW BOXED BOYFRIEND BUBBLY BUZZING BYPRODUCT BYSTANDER BYZANTINE CAPPUCCINO CATTLE CENT CICERO COCCYX COOKED COPYRIGHT COYOTE CROQUET CUMBERSOME CYCLE CYLINDER CZECH DABBLE DADDY DAY DIVIDE DON'T DR DURING DYKE EACH EBB EEK ELEPHANT EMBLEM ENSNARE EPIPHANY ESQUIRE ETCHING EQUINE FARMING FEARED FILLER FIZZY FABRIC FARMING FEARED FILLER FINGER FJORD FLUID FOGGY FOXXY FRONTAL FUNGAL GAGGLE GEARED GNOME GRUBBY HAPPENED HAPPINESS HAZY HELLISH HIGH HOPE HUNGRY HYPHEN ICY I'M IMPOSSIBLE INTOLERANT IT'S I'VE JAZZY JAGGED JENGA JILL JOINT JUST KANGAROO KETTLE KITCHEN KNACK KOALA KOOKY LABORATORY LANDING LEFT LETTER LIKELY LILAC LITTLE LOCO LOLLY LOVER'S LUNA LUXURIOUS LYING MASTER MATTER METRES MISS MOONLIGHT MORPH MR MRS MS MUMMY MUSTER NASAL NEANDERTHAL NECESSARILY NINE NONSENSE NOON NUMB OAR OBFUSCATE OCCULT ODDLY OFTEN OGRE OKAY OMISSION OZONE PARALLEL PEAR PICNIC PNEUMONIC POPPY POROUS PYGMY QUANTUM QUEEN QUINCE QUOTA RADII RAFFERTY RATTLE REASSURE RESIST RETIREE RICE ROOMMATE RUNNING SASSAFRAS SAVVY SCENT SCUTTLE SEISMIC SHINING SHOOK SIEVE SISTER SKINK SLUMP SNIDE SOUP SPIRE STAY SUBJECT SULTANA SVELTE SWIFTLY TALLIED TATTOOED TAXED TENSION THE THEATRE TITLE TOTALLY TREKKED TSUNAMI TUTOR TYING UDDER UGLY ULCER UMBRELLA UNDER USURP UTTERLY VACUUM VARIABLE VENT VIVID VOID VULNERABLE VYING WAFFLE WALLY WARRANTED WATER WEATHER WHALE WINCE WITHHELD WORRY WURST WYSIWYG WYVERN XENON XMAS YAK YEAH YIP YOU'RE YUCK ZAC ZEAL ZIGZAG ZING ZODIAC ZOO \n"

// "Av Aw Ay Az Fa Fe Fi Fo Fu Kv Kw Ky Pa Pe Po Ta Te Ti To Tr Ts Tu Ty Va Ve Vj Vo Vr Vu Vy Wa We Wr Wv Wy \n"
// "AC AT AVA AWA AYA AV AW AY AZ CT CYC FA FE FO KV KW KY LO LV LY NG OD PA PA PE PO TA TA TE TI TO TR TS TU TY UA VA VA VE VO VR VU VY WA WO WA WE WR WV WY YS \n"
// "vj"
;

const int word_pair_count = 53;
char word_pairs[word_pair_count*word_pair_count*3 + 1];
char word_pairs_single[53*3+1];

char* words_get_pairs() {
    for (int a = 0; a < word_pair_count; ++a) {
        int aa = a>25 ? a+6 : a;
        if (a==(word_pair_count-1)) aa = '\''-'A';
        for (int b = 0; b < word_pair_count; ++b) {
            int bb = b>25 ? b+6 : b;
            if (b==(word_pair_count-1)) bb = '\''-'A';
            word_pairs[(a*word_pair_count*3) + (b*3)] = 'A'+aa;
            word_pairs[(a*word_pair_count*3) + (b*3) + 1] = 'A'+bb;
            word_pairs[(a*word_pair_count*3) + (b*3) + 2] = b==(word_pair_count-1)?'\n':' ';
        }
    }
    word_pairs[array_size(word_pairs)-1] = 0;
    return word_pairs;
}

char* words_get_pairs_for(char c) {
    FOR (i, 53) {
        word_pairs_single[i*3] = c;
        word_pairs_single[i*3 + 1] = 'A'+i + (i>25 ? 6 : 0);
        word_pairs_single[i*3 + 2] = ' ';
        if (i==52) {
            word_pairs_single[i*3 + 1] = '\'';
        }
    }
    word_pairs_single[array_size(word_pairs_single)-1] = 0;
    return word_pairs_single;
}